spring.application.name=${APPLICATION_NAME}

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

storage.endpoint=${STORAGE_ENDPOINT}
storage.bucket=${STORAGE_BUCKET}
storage.region=${STORAGE_REGION}

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

authentication.access-secret=${ACCESS_SECRET}
authentication.refresh-secret=${REFRESH_SECRET}
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB
